-- Seed Properties for billleynyuy@gmail.com
-- Run this SQL in your Supabase SQL Editor

-- First, let's check if the user exists and get their ID
-- Replace 'f3d83a7b-b983-4ab5-bae4-f180272812b2' with the actual UUID of the user billleynyuy@gmail.com

-- You can find the user ID by running this query first:
-- SELECT id, email FROM auth.users WHERE email = 'billleynyuy@gmail.com';

-- Then replace 'f3d83a7b-b983-4ab5-bae4-f180272812b2' below with the actual UUID

INSERT INTO public.properties (
    owner_id,
    title,
    description,
    property_type,
    listing_type,
    status,
    price,
    currency,
    address,
    city,
    region,
    latitude,
    longitude,
    bedrooms,
    bathrooms,
    area_sqm,
    furnished,
    parking,
    garden,
    swimming_pool,
    security,
    internet,
    electricity,
    water,
    contact_phone,
    contact_email,
    featured,
    verified
) VALUES 
-- Modern Family Villa in Bamenda
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Modern Family Villa in Bamenda',
    'Beautiful 4-bedroom villa with stunning mountain views. Features include modern kitchen, spacious living areas, and well-maintained garden.',
    'villa',
    'sale',
    'available',
    85000000.00,
    'XAF',
    'Mile 4 Nkwen, Upper Quarters',
    'Bamenda',
    'North West',
    5.9597,
    10.1453,
    4,
    3,
    280.50,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    true,
    true
),
-- Downtown Apartment for Rent
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Downtown Apartment for Rent',
    'Cozy 2-bedroom apartment in the heart of Douala. Perfect for young professionals or small families.',
    'apartment',
    'rent',
    'available',
    180000.00,
    'XAF',
    'Akwa District, Rue Joss',
    'Douala',
    'Littoral',
    4.0511,
    9.7679,
    2,
    1,
    95.00,
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    false,
    true
),
-- Commercial Building
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Commercial Building - Prime Location',
    'Three-story commercial building perfect for offices or retail space. Located in busy commercial district.',
    'commercial',
    'sale',
    'available',
    125000000.00,
    'XAF',
    'Commercial Avenue, Central Business District',
    'Yaoundé',
    'Centre',
    3.8480,
    11.5021,
    0,
    4,
    450.00,
    false,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    true,
    true
),
-- Beachside House
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Beachside House in Limbe',
    'Charming 3-bedroom house just 200m from the beach. Perfect for vacation rental or permanent residence.',
    'house',
    'sale',
    'available',
    65000000.00,
    'XAF',
    'Mile 1, Beach Road',
    'Limbe',
    'South West',
    4.0156,
    9.2145,
    3,
    2,
    160.00,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    false,
    false
),
-- Student Apartment
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Student Apartment Near University',
    'Affordable 1-bedroom apartment perfect for students. Close to University of Buea campus.',
    'apartment',
    'rent',
    'available',
    85000.00,
    'XAF',
    'Molyko, University Street',
    'Buea',
    'South West',
    4.1563,
    9.2924,
    1,
    1,
    45.00,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    false,
    true
),
-- Luxury Office Space
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Luxury Office Space',
    'Premium office space in the heart of Douala business district. Fully equipped with modern amenities.',
    'office',
    'rent',
    'available',
    750000.00,
    'XAF',
    'Bonanjo District, Independence Avenue',
    'Douala',
    'Littoral',
    4.0483,
    9.7043,
    0,
    2,
    120.00,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    true,
    true
),
-- Agricultural Land
(
    'f3d83a7b-b983-4ab5-bae4-f180272812b2',
    'Agricultural Land - Fertile Farmland',
    'Prime agricultural land suitable for various crops. Access to water source and good road network.',
    'land',
    'sale',
    'available',
    25000000.00,
    'XAF',
    'Ndu Road, Agricultural Zone',
    'Kumbo',
    'North West',
    6.2088,
    10.6713,
    0,
    0,
    5000.00,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    '+237 677 123 456',
    'billleynyuy@gmail.com',
    false,
    true
);
