// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfwkmmjzrgdgahftaljj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmd2ttbWp6cmdkZ2FoZnRhbGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODExNzIsImV4cCI6MjA3MjU1NzE3Mn0.QPSpy6mKfORQLRmbBEt_bceVvPExG5HQP6yTh-qISHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});